# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=znver1 -O3 -pipe -flto"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

CC="clang"
CXX="clang++"

RUSTC_WRAPPER=/usr/bin/sccache
SCCACHE_DIR=/var/cache/sccache
SCCACHE_MAX_FRAME_LENGTH=104857600

LC_MESSAGES=C

#MAKEOPTS="--jobs 12 --load-average 13"
#EMERGE_DEFAULT_OPTS="--jobs 12 --load-average 13"
MAKEOPTS="--jobs 8 --load-average 9"
EMERGE_DEFAULT_OPTS="--jobs 8 --load-average 9"

LUA_TARGETS="lua5-4"

#ACCEPT_KEYWORDS="~amd64"

VIDEO_CARDS="amdgpu radeonsi"
INPUT_DEVICES="libinput"

FEATURES="parallel-install buildpkg"
#FEATURES="test keeptemp"

L10N="en"

LINGUAS="en"
