# enable auto-completion
autoload -U compinit promptinit
compinit
promptinit; prompt gentoo

# completion style
zstyle ':completion:*' menu select

# use cache for completion
zstyle ':completion::complete:*' use-cache 1

# enable auto-correction
setopt correctall

# use emacs bindings
bindkey -e 

# bindings
bindkey  "^[[H"     beginning-of-line
bindkey  "^[[F"     end-of-line
bindkey  "^H"       backward-kill-word
bindkey  "^[[3;5~"  kill-word

# enable history
export HISTSIZE=2000
export HISTFILE="$HOME/.cache/zsh_history"

# save history
export SAVEHIST=$HISTSIZE

# history ignore duplicates
setopt hist_ignore_all_dups

# easier cd
setopt autocd

# syntax highlighting
source /usr/share/zsh/site-functions/zsh-syntax-highlighting.zsh
